// Code generated by generate-named. DO NOT EDIT.

package named

// testStructNamed provides methods to access field names of TestStruct
type testStructNamed struct{}

func (testStructNamed) Field1() string { return "field1" }
func (testStructNamed) Field2() string { return "field2" }

// TestStructNamed is the exported variable for accessing TestStruct field names
var TestStructNamed testStructNamed

// personNamed provides methods to access field names of Person
type personNamed struct{}

func (personNamed) Name() string  { return "name" }
func (personNamed) Age() string   { return "age" }
func (personNamed) Email() string { return "email" }

// PersonNamed is the exported variable for accessing Person field names
var PersonNamed personNamed

// userNamed provides methods to access field names of User
type userNamed struct{}

func (userNamed) ID() string       { return "user_id" }
func (userNamed) Username() string { return "username" }
func (userNamed) Active() string   { return "is_active" }

// UserNamed is the exported variable for accessing User field names
var UserNamed userNamed

// productNamed provides methods to access field names of Product
type productNamed struct{}

func (productNamed) SKU() string         { return "sku" }
func (productNamed) Name() string        { return "product_name" }
func (productNamed) Price() string       { return "price" }
func (productNamed) Description() string { return "Description" }

// ProductNamed is the exported variable for accessing Product field names
var ProductNamed productNamed
